name: Documentation

on:
  push:
    tags:
      - "*"

env:
  CPM_SOURCE_CACHE: ${{ github.workspace }}/cpm_modules

jobs:
  build:
    name: Build and publish documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v2
        with:
          path: "**/cpm_modules"
          key: ${{ github.workflow }}-cpm-modules-${{ hashFiles('**/CMakeLists.txt', '**/*.cmake') }}

      - name: "Set up Python 3"
        uses: actions/setup-python@v2
        with: 
          python-version: '3.x'

      - name: Install dependencies
        run: |
          sudo apt-get install -y doxygen
          pip install -r requirements_dev.txt

      - name: Build
        run: |
          cmake -Sdocumentation -Bbuild
          cmake --build build --target GenerateDocs

      - name: Publish
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/doxygen/html